.gitattributes, .github/workflows/git-push.yml, .husky/commit-msg, build.sh, src/app/(route)/layout.tsx, src/provider/QueryProvider.tsx
- husky commit-msg 파일 변경
- `.gitattributes`파일 추가
- github action 설정
- 이슈 번호: #13 
`husky/commit-msg` 파일에서 윈도우에서는 끝 줄을 LF 방식으로 변경, `.gitattributes` 파일 추가해서 끝 줄을 auto로 맞췄습니다.
gitgub action 설정해서 제 개인 레포로 포크해서 vercel 연동해서 배포 해놨습니다.
https://front-sooty-three.vercel.app/
`.gitattributes` 관련 내용
https://docs.github.com/ko/get-started/getting-started-with-git/configuring-git-to-handle-line-endings?platform=mac
vercel 배포 관련 내용
https://jjang-j.tistory.com/93
https://velog.io/@newjin46/Next.js-Vercel%EB%A1%9C-GitHub-Organization-%EB%AC%B4%EB%A3%8C-%EB%B0%B0%ED%8F%AC%ED%95%98%EA%B8%B0-with-github-actions
=> [Setting] vercel deploy 설정

package.json, pnpm-lock.yaml, src/utils/className.ts
- clxs, cva, twMerge 라이브러리 설치 및 유틸함수 생성
- 이슈 번호: #15 
- clsx, cva, twMerge 라이브러리 설치했습니다.
- `utils/className.ts` 파일에 cn 유틸함수 만들었습니다.
https://dev-102.tistory.com/entry/Tailwind-CSS-%EC%9E%98-%ED%99%9C%EC%9A%A9%ED%95%98%EA%B8%B0-with-Clxs-CVA-twMerge
https://velog.io/@qwzx16/tailwind%EB%A5%BC-%EC%9D%B4%EC%9A%A9%ED%95%9C-%ED%9A%A8%EC%9C%A8%EC%A0%81%EC%9D%B8-React-Component-%EA%B4%80%EB%A6%ACtailwind-merge-cva-clsx-%ED%8C%8C%ED%97%A4%EC%B9%98%EA%B8%B0
=> [Setting] tailwind 추가 라이브러리 세팅

.storybook/main.ts, src/components/common/Chip/Chip.stories.ts, src/components/common/Chip/Chip.tsx
- react icons 라이브러리 추가
- storybook staticDirs 변경
- Chip 컴포넌트 제작
- Chip 컴포넌트 스토리북 제작
- 이슈 번호: #26 
Chip 컴포넌트를 만들었습니다.
`variant`로 `default`, `action` 값을 기준으로 변경이 가능합니다.
`size`로 `sm`, `lg` 값을 기준으로 변경이 가능합니다
`children`으로 내부 텍스트를 전달하면 됩니다.
onClick 핸들러를 외부에서 만들어서 적용시키면 적용됩니다.
수정해야될 부분 있으면 말해주세요
=> [Feat] create chip component

.github/workflows/storybook.yml, package.json, pnpm-lock.yaml
- Storybook Chromatic 배포
- Git Actions을 통한 PR 시 자동 배포 설정
- 이슈 번호: #50 
[Storybook 공식분서 - 배포](https://storybook.js.org/tutorials/intro-to-storybook/react/ko/deploy/)
[Chromatic으로 storybook 배포](https://jjang-j.tistory.com/138)
=> [Setting] stroybook chromatic 배포(Git Actions, CICD)

src/app/(route)/page.tsx, src/components/common/Button/Button.stories.ts, src/components/common/Button/Button.tsx, src/components/common/Spinner/index.tsx
- Button 컴포넌트 구현했습니다.
- Button 컴포넌트에 사용할 스피너 구현했습니다.
- Storybook 작성했습니다.
- 이슈 번호: #40 
props가 좀 많아졌는데, 전부 기본값이 존재하다 보니 `children`만 작성하시면 쓰실 수 있습니당
후에 `tanstack query`를 사용할 때, `pending`일 시 사용자 경험을 개선하기 위하여 `disabled`과는 다르게 처리해봤습니다.
=> [Feat] create button component

src/app/(route)/dashboard/page.tsx, src/components/Dashboard/Circle/index.tsx, src/components/Dashboard/ProgressCircle/index.tsx, src/components/common/Header/index.tsx
- Header 컴포넌트 title 스타일 적용
- Dashboard 페이지 ui 제작
- 이슈 번호: #55 
title 부분 style 적용
주소는 `/dashboard`로 해두었습니다.
ui 변경점이 많을 것 같다는 `최근 등록한 할 일`, `진행 상황 그래프` 부분은 일단 레이아웃만 잡아두었습니다.
`목표 별 할일` 부분엔 다음 이슈로 목업 데이터 적용시켜보겠습니다.
=> [Feat] create dashboard page UI

next.config.ts, package.json, pnpm-lock.yaml
-  bundle analyzer install
- next.config에 적용
- dynamic import를 통한 성능 개선(이미 해서 나중에 추가로 할 예정 ㅎㅎ... Toast에서 했습니당 아마도)
- 이슈 번호: #72 
```
NEXT_PUBLIC_ANALYZE=true pnpm build
```
.env에 추가하셔야 잘 돌아갈거에용 build 시에만 돌아가게 해뒀습니다
만약... 잘 안 돌아간다면 잠시 묻어두고 나중에 lighthouse와 같이 최적화 진행할 때 다시 살려볼게요
=> [Setting] bundle analyzer를 사용한 번들 크기 확인 및 최적화

src/app/(route)/page.tsx, src/components/SelectionModal/index.tsx, src/components/common/ModalContainer/index.tsx
- SelectionModal 구현
- 이슈 번호: #94 
SelectionModal 만들어봤어요
- createPotal 사용해서 구현했습니다
- Modal 관련해서 motion 적용해서 css 개선해봤어요
- 앨범 선택, 촬영 선택하는 모달이였는데 너무 이거만 구현하면 여러 기능을 못 할 거 같아 일단 확장시켜봤습니다... 원하는 정도로 나오지는 않았는데 지금 상황이 상황인지라 일단 올렸어요
- useEffect로 모달이 열렸을 시 외부 스크롤 제한 걸어봤습니다 후에 모달이 더 늘어나면 hook으로 분리해도 괜찮을 거 같아요
- props 이름이 그닥 마음이 안 드는데 적당한 이름 추천해주세요(cancelButtonMessage 진짜구림)
- 나머지는 코드 짧으니까 읽어보시면 될 거 같아여...
=> [Feat] create SelectionModal

src/components/AuthPage/Logo/index.tsx, src/components/TodoModal/TodoModalGoal/index.tsx
- [todoModal Goal 기존 mockData에서 내 목표 데이터로 수정](https://github.com/slid-todo/front/commit/ce99876285fe9e9bba652c259166ebdd6f5618db)
- 임시 로고
- 이슈 번호: #95 
useSidebarGoalsQuery의 goals 데이터를 사용하였습니다.
react-icons의 쥐모양의 아이콘을 일단 넣어두었습니다.
=> [Feat] add goals data in Todomodal

src/components/Dashboard/GoalList/GoalItem/GoalHeader/index.tsx, src/components/Dashboard/GoalList/GoalItem/ProgressLine/index.tsx, src/components/Dashboard/GoalList/GoalItem/TodoList/TodoPic/index.tsx, src/components/Dashboard/GoalList/GoalItem/TodoList/index.tsx, src/components/Dashboard/GoalList/GoalItem/index.tsx, src/components/Dashboard/GoalList/index.tsx, src/components/Dashboard/RecentTodos/index.tsx, src/components/Sidebar/index.tsx, src/components/TodoModal/TodoModalGoal/index.tsx, src/components/Todos/TodoItem.tsx, src/hooks/apis/Dashboard/useRecnetTodosQuery.ts, src/hooks/apis/Dashboard/useTodosOfGoalsQuery.ts, src/hooks/apis/useGoalsQuery.ts, src/lib/axiosInstance.ts
- 목표에 맞는 색상 적용 (최근 등록한 할 일, 목표 별 할일)
- 이슈 번호: #99 
목표에 맞는 색상을 적용했습니다.
=> [Refactor] apply dashboard color

src/lib/axiosInstance.ts, src/middleware.ts
- next js 미들웨어 설정
- axios 인터셉터 제거
- 이슈 번호: #113 
도메인 설정 후 쿠키 토큰을 받아와 값이 유효한 경우 미들웨어 설정을 해주었습니다.
기존 401에러 관련 인터셉터 코드를 제거하였습니다.
=> [Refactor] 미들웨어 설정 및 axio 인터셉터 제거

.env, .gitignore, src/components/Dashboard/GoalList/GoalItem/GoalHeader/index.tsx
- 대시보드 zustand selector function 적용
- env 파일 추가
- 이슈 번호: #118 
현재 대시보드에서 모달을 띄우면 모달 내부의 값을 변경할 때마다 뒤의 대시보드 목표의 헤더부분이 리렌더링 되는 부분을 수정했습니다.
zustand의 selector function으로 불러와서 사용하는 방법으로 했습니다.
서버 주소를 포함한 env 파일 추가
기존
https://github.com/user-attachments/assets/fa0c1847-3935-4957-af9a-df5a6486a87d
변경 후
https://github.com/user-attachments/assets/290b4128-d947-4fcd-b1de-b1719607aa1e
제 블로그 임니다
https://velog.io/@eui-jin/Zustand-%EB%A0%8C%EB%8D%94%EB%A7%81-%EC%B5%9C%EC%A0%81%ED%99%94
=> [Refactor] refactor zustand function in goal header

next.config.ts, src/components/Sidebar/Profle/index.tsx, src/hooks/apis/useUserQuery.ts
- 사이드바에 유저 프로필 적용
- 이슈 번호: #129 
`next/image`의 Image 컴포넌트 사용해서 유저 프로필을 보이도록 했습니다.
스켈레톤 적용시켜서 로딩중일 땐 스켈레톤 뜨도록 했습니다.
`setTimeout` 사용해서 로딩이 빠를 때는 스켈레톤이 뜨지 않도록 구현했습니다.
`next.config.ts` 파일에 저희 서버 이미지 주소 등록했습니다.
인터넷 느릴 때 (3G) 
https://github.com/user-attachments/assets/5e3edb5f-4b7c-4182-b88d-6566c5222fa7
인터넷 빠를 때
https://github.com/user-attachments/assets/8e973280-6bf1-4c07-9bd0-2339ee8d5715
=> [Feat] Add user profile in sidebar

src/components/Sidebar/GoalList/index.tsx, src/components/Sidebar/index.tsx, src/hooks/apis/Sidebar/useSidebarGoalsMutation.ts
- 사이드바 목표 최신순 3개로 변경
- 이슈 번호: #131
사이드바 컴포넌트 내부에서 최신순 3개로 정렬 후 필터링 하는 방식으로 적용시켰습니다.
새로 추가되는 목표도 최상단으로 옮겨져서 낙관적 업데이트 위치도 변경했습니다.
https://github.com/user-attachments/assets/58046c58-345a-4e24-aeb6-546d4fe83d20
126번 브랜치 리베이스 후 사용중이라 126번 머지되면 main으로 리베이스 할 예정입니다.
=> [Refactor] refactor sidebar goals recent three

__test__/formatDateToPoint.spec.ts, __test__/formatDateToRelativeTime.spec.ts, __test__/init.spec.ts, jest.config.ts, package.json, pnpm-lock.yaml, src/utils/date.ts
- formatDateToPoint test 코드 작성
- gormatDateToRelativetime test code 작성
- 이슈 번호: #133 
일단 utils 폴더 안의 함수만 테스트 해서 `jest`만 세팅 해두었습니다.
`__test__` 폴더 안에 작성했습니다. 
> 이 부분은 추후에 정해야할 것 같습니다.
`date.ts` 안의 함수만 jest로 테스트 했습니다.
=> [Feat] add jest test for function in utils function

src/apis/Todo/convertImageToBase64.ts, src/apis/Todo/modifyTodo.ts, src/app/(route)/page.tsx, src/components/TodoModal/TodoModalContainer/index.tsx, src/components/TodoModal/TodoModalDocs/FileUpload/index.tsx, src/components/TodoModal/TodoModalDocs/index.tsx, src/components/TodoModal/TodoModalGoal/DropdownIcon/index.tsx, src/components/TodoModal/TodoModalGoal/index.tsx, src/components/TodoModal/TodoModalHeader/StatusButton/index.tsx, src/components/TodoModal/TodoModalHeader/index.tsx, src/components/TodoModal/TodoModalRepeat/index.tsx, src/constants/Todos/CommonTodoData.ts, src/hooks/apis/Todo/useModifyTodo.ts, src/types/Todos/ModifyTodos/TodoStatus.ts, src/utils/todoDataValidation.ts
- 할일 삭제, 할일 수정을 위한 todoId 추가
- TodoStatus에 관한 체크박스 추가
- 할 일 수정시 TodoStatus, 날짜, 이미지 데이터 동기화
- aws s3 이미지 -> base 64 변환 로직 
- 이미지 제거 처리 아이콘 추가
- 이슈 번호: #127 
aws s3 이미지 -> base 64 변환 로직은 put 요청이기에 내가 이미지를 변경하지 않았음에도 불구하고 다시 보내야되기 때문에
이미지를 변경하면 base 64로 변경되어서 상관없지만
변경을 하지않으면 그대로 s3이미지 링크가 들어가있어 이를 변경할 필요가 있었음.
또한 수정인 경우는 목표를 변경하지 못하도록 처리
mockData를 이용하여 테스트를 진행하였습니다.
=> [Refactor] 할일 수정 로직 수정 및 테스팅

src/apis/services/httpMethod.ts, src/components/Dashboard/GoalList/index.tsx, src/components/Sidebar/index.tsx, src/hooks/apis/Dashboard/useRecnetTodosQuery.ts, src/hooks/apis/Dashboard/useTodayProgressQuery.ts, src/hooks/apis/Dashboard/useTodosOfGoalsQuery.ts, src/hooks/apis/Goals/useGoalsDetailQuery.ts, src/hooks/apis/Todo/useCreateTodo.ts, src/hooks/apis/useGoalsQuery.ts, src/hooks/apis/useUserQuery.ts, src/types/pageable.ts
- 목표 별 할 일 API 타입 수정
- 대시보드 무한 스크롤 적용
- 기타 개선
- 이슈 번호: #135
`BasePageableTypes`를 만들어 스크롤 기본 타입 설정하였습니다.
`useInfiniteQuery` 사용해서 구현하였습니다. 
```js
export const todosOfGoalsOptions = (): UseInfiniteQueryOptions<
TodosOfGoalsResponse,
AxiosError,
InfiniteQueryResponse
> => ({
queryKey: [QUERY_KEYS.TODOS_OF_GOALS],
queryFn: ({ pageParam = 0 }) =>
GET<TodosOfGoalsResponse>(
`${API_ENDPOINTS.TODOS.GET_GOALS}?lastGoalId=${pageParam}&size=3`,
),
getNextPageParam: (lastPage) => {
const nextCursor = lastPage.data.nextCursor;
return nextCursor !== 0 ? nextCursor : undefined;
},
initialPageParam: 0,
});
export const useTodosOfGoalsQuery = () => {
const { data, ...etc } = useInfiniteQuery(todosOfGoalsOptions());
const goals = data?.pages.flatMap((page) => page.data.content) ?? [];
return { goals, ...etc …
```
=> [Refactor] apply changed api for dashboard todos of goals

src/components/Goals/GoalList/GoalHeader/index.tsx
- 목표 페이지 접근성 개선
- 이슈 번호: #175
목표 페이지의 메뉴 버튼에 `aria-label` 추가했습니다.
아이콘에` aria-hidden `추가했습니다
> Accessibility 점수가 89점에서 95점으로 증가했습니다.
=> [Feat] Add aria label in goals page

src/app/layout.tsx
- Google SEO 메타태그 추가
- 이슈 번호: #184 
Google Search Console에서 메타태그 받아서 추가했습니다.
변경 사항을 시각적으로 확인할 수 있는 스크린샷을 여기에 첨부해주세요.
https://dsoob.com/58/?bmode=view&idx=11656678
=> [Feat] Add google seo meta tag

src/app/not-found.tsx
- 404 페이지 제작
- 이슈 번호: #145 
홈으로 가기, 뒤로가기 설정을 해주었습니다.
디자인에 소질이 없다는 것을 알고있습니다.
=> Feat: 404 페이지 제작
