- src/app/(route)/GiBeom/page.tsx
- src/components/common/Modal/ModalContainer/index.tsx
- src/components/common/Modal/TodoModal/TodoModalDocs/LinkUpload/index.tsx
- src/components/common/Modal/TodoModal/TodoModalHeader/index.tsx
- src/components/common/Modal/TodoModal/TodoModalRepeat/index.tsx
- src/components/common/Modal/TodoModal/index.tsx
- src/constants/Placeholders.ts
- src/store/useTodoModalStore.ts
- src/types/TodoType.ts
- [TodoModal 열림 상태 store 생성 및 관리](https://github.com/slid-todo/front/commit/c8a0202ce8b8f507cc0eab039293eaf6af307dbe)
- [반복 설정에 관한 컴포넌트 추가](https://github.com/slid-todo/front/commit/a242009533629c0b84cae5ebbc872a120bd060cb)
- [cn 유틸 함수 사용](https://github.com/slid-todo/front/commit/cfa3cb2f1b8bffa273f401e44e4ad3f9188ffc9c)
- 이슈 번호: #36 
TodoModal 열림 상태를 기본 useState 사용에서 zustand store 사용으로 변경
반복 설정에 관한 input이 누락되어 변경
cn 유틸 함수를 이용하여 아이콘 클릭에 관한 디자인 변경 클래스 생성
이전 PR과 동일
> [Feat] 할 일 모달 리팩토링 및 기능 추가 (Zustand, 반복주기 설정 등)

- .storybook/main.ts
- package.json
- pnpm-lock.yaml
- src/components/common/Chip/index.tsx
- src/components/common/Input/index.stories.ts
- src/components/common/Input/index.tsx
- Input 컴포넌트 제작
- Input 컴포넌트 스토리북 제작
- 이슈 번호: #37 
Input 컴포넌트를 만들었습니다.
사이즈를 특정해서 만들기가 어려워서 일단 width 값은 className으로 넘겨주면 원하는 값으로 사용가능합니다.
> 기본값으로는 `w-full`이 들어가있습니다.
`ref`를 사용할 수 있도록 prop에 ref도 추가시켜놨습니다. (제어 / 비제어)
현재 피그마 상에서 input 컴포넌트 배경색이 흰색이라 스토리북 배경색을 변경했습니다.
그에 따른 스토리북 추가 라이브러리 다운 받았습니다.
mdx 파일로 스토리북 사용해보고 싶은데 적용이 안되서 다른 방법으로 작성해두었습니다.
> [Feat] create input component

- src/app/(route)/dashboard/page.tsx
- src/components/Dashboard/DashboardItemContainer/index.tsx
- src/components/Dashboard/Follwer/index.tsx
- src/components/Dashboard/GoalList/GoalItem/TodoList/index.tsx
- src/components/Dashboard/GoalList/index.tsx
- src/components/Dashboard/MyProgress/ProgressCircle/index.tsx
- src/components/Dashboard/MyProgress/index.tsx
- src/components/Dashboard/RecentTodos/index.tsx
- src/components/common/Card/index.tsx
- src/components/common/Header/index.tsx
- src/constants/DashboardMockData.ts
- 팔로우 현황 추가
- 목표나 할일이 없을 때의 레이아웃 추가
- 이슈 번호: #75
현재는 후순위 개발이라 항상 비어있는 화면으로 설정해두었습니다.
각각에 맞는 카드를 배치해두었습니다.
헤더에 알람 아이콘 설정해두었습니다.
피그마엔 색상이 회색으로 되어있는데 primary 색이 조금 더 잘 어울려서 일단 해두었습니다.
할일 인증 사진 부분은 api 연동하면서 작업해야할 것 같습니다.
> [Refactor] add empty data dashboard page

- src/apis/Auth/signin.ts
- src/apis/Sidebar/getSidebarGoals.ts
- src/apis/Todo/createTodo.ts
- src/hooks/apis/useSignin.ts
- src/lib/axiosInstance.ts
- 응답 헤더를 통해 토큰을 방식으로 로그인 로직을 변경하였습니다.
- 토큰을 local storage에 저장하는 방식으로 진행하였습니다. 
- 이슈 번호: #83 
axiosInstance 파일에서 토큰 관련 인터셉터 코드를 추가하였습니다.
로그인 mutation 훅에서 성공 시 헤더의 토큰을 저장하는 로직으로 구성하였습니다.
> [Refactor] login api for header token

- src/hooks/apis/Auth/useSignin.ts
- src/lib/axiosInstance.ts
- 후우.. 쿠키로 토큰을 불어와지는 것은 잘되었으나 서버와의 도메인이 달라 middleware에서 토큰을 불러올 수 없었습니다.
[https://velog.io/@jojeon4515/서로-다른-도메인에서-쿠키-사용하기-React-Express](https://velog.io/@jojeon4515/%EC%84%9C%EB%A1%9C-%EB%8B%A4%EB%A5%B8-%EB%8F%84%EB%A9%94%EC%9D%B8%EC%97%90%EC%84%9C-%EC%BF%A0%ED%82%A4-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0-React-Express)
- 결국 axiosInstance에서 401(인증 오류)가 떴을 때 라이렉션해주는 방법으로 선택
- 로그인 성공 시 대시보드 페이지로 이동
- 이슈 번호: #71 
변경 사항을 시각적으로 확인할 수 있는 스크린샷을 여기에 첨부해주세요.
이 부분에 대해서는 멘토님에게 피드백을 받아봐야할 것 같습니다.
> [Refactor] 로그인 성공시 페이지 이동 및 axios 인스턴스로 리다이렉션

- src/hooks/apis/Todo/useCreateTodo.ts
- 할 일 생성 성공 시에 쿼리 무효화를 통해 실시간으로 변하도록 수정 후 모달 닫기
- 이슈 번호: #100 
자세한 변경 사항을 여기에 작성해주세요. 왜 이러한 변경이 필요한지, 어떻게 구현했는지 등을 포함합니다.
notify 두줄이 거슬리네요...
> [Refactor] 할일 생성 성공 시 쿼리키 무효화 후 모달 닫기

- src/apis/getGoals.ts
- src/apis/services/httpMethod.ts
- src/components/Sidebar/Profle/index.tsx
- src/constants/ApiEndpoints.ts
- src/constants/QueryKeys.ts
- src/hooks/apis/useGoalsQuery.ts
- src/hooks/apis/useUserQuery.ts
- 사이드바 유저정보 api 연동
- 공통 http method 함수 생성
- 이슈 번호: #105 
`/hooks/api/useUserQuery` 로 `email`, `name` 불러오도록 구현하였습니다.
`/apis` 폴더 안에 따로 정리할 필요 없이 `hooks/apis` 폴더 안에 `useQuery`, `useMutation` 사용하는 훅 만들 때 가져와서 사용할 수 있도록 했습니다.
대부분의 응답이 `data`만 받아오기 때문에 `data`만 받아올 수 있도록 했고 에러 처리는 `axios`의 `interceptor`가 공통적으로 하거나 `react query`의 `onError`로 설정할 수 있습니다.
> signin, signup 부분은 header의 쿠키값을 가져와야해서 적용이 될지는 잘 모르겠습니다ㅠ
> MVP 이후에 이 방식으로 수정하거나 다른 좋은 방식이 있으면 해당 방식으로 수정하면 될 것 같습니다.
**GET 예시**
```js
const userInfoOptions: UseQueryOptions<UserInfoResponse, AxiosError> = {
queryKey: [QUERY_KEYS.USER_INFO],
queryFn: () => GET<UserInfoResponse>(API_ENDPOINTS.AUTH.USER),
};
```
> [Feat] create user info in sidebar

- src/app/(route)/dashboard/page.tsx
- src/components/Dashboard/RecentTodos/index.tsx
- src/components/Sidebar/MenuItem/index.tsx
- src/components/Sidebar/index.tsx
- src/components/common/Skeleton/index.tsx
- src/hooks/apis/Dashboard/useRecnetTodosQuery.ts
- src/hooks/apis/Dashboard/useTodayProgressQuery.ts
- src/hooks/apis/Dashboard/useTodosOfGoalsQuery.ts
- src/hooks/apis/Sidebar/useSidebarGoalsMutation.ts
- 최근 내 할일 스켈레톤 추가
- 새로운 목표 추가 시 대시보드 갱신
- 목표가 없을 때 버튼 추가
- 할일만 없을 때 버튼 추가
- 이슈 번호: #105 
공통 스켈레톤 컴포넌트 만들어서 추가했습니다.
새로운 목표를 추가했을 때 대시보드 갱신하도록 수정했습니다.
대시보드에서 목표가 없을 때 사이드바 열리도록 수정
대시보드에서 할일이 없을 때 새 할일 생성 모달 열리도록 수정
> [Refactor] Fix QA

- src/components/Dashboard/GoalList/GoalItem/GoalHeader/index.tsx
- src/components/Dashboard/GoalList/GoalItem/index.tsx
- src/components/Dashboard/GoalList/index.tsx
- src/components/TodoModal/TodoModalGoal/index.tsx
- src/hooks/apis/Todo/useCreateTodo.ts
- src/lib/axiosInstance.ts
- src/store/useTodoDataStore.ts
- 목표별 할일에서 목표에 있는 할일 추가 버튼을 누르면 할 일 생성에 있는 목표의 값이 자동으로 바뀌도록
- test 완료
- 이슈 번호: #111 
의진님이 작업하신 GoalList, GoalItem, GoalHeader에 id props를 추가하였습니다.
목표 주제가 zustand 저장소 실제 전송 데이터에 포함되어있어서 이를 분리하고 따로 관리하도록 하였습니다.
> [Refactor] Sync Goal Value on Add Task Button Click

- src/apis/Auth/signin.ts
- src/lib/axiosInstance.ts
- src/middleware.ts
- src/store/useTokenStore.ts
- 토큰을 쿠키에서 헤더로 변경
- 이슈 번호: #121 
기존 쿠키로 관리하던 토큰을 헤더로 다시 변경하였습니다.
토큰 관리에 대해 찾아본 결과 일단은 로그인 했을 때 
accessToken은 보안 위험 때문에 메모리에서 관리, 쿠키에 HttpOnly, Secure, SameSite 설정해서 관리하는 방법이 있고
refreshToken은 노출되어도 상관 없는 값이라 쿠키에서 관리하는 방법으로 이해했습니다.
저희가 현재 관리하고 있는 토큰은 accessToken이라 생각되어 zustand로 저장하여 관리하는 방식으로 했습니다.
> 새로고침 하면 메모리에 저장된 값이라 사라져서 다시 로그인 해야됩니다..
> 미들웨어는 이후 수정을 위해 주석처리 해두었습니다.
신지수님 블로그 참고
https://new-development.tistory.com/15
> [Refactor] change token handling cookie to header

- src/apis/Todo/certifiedTodo.ts
- src/app/(route)/todos/page.tsx
- src/components/CertifiedModal/index.tsx
- src/components/Dashboard/RecentTodos/index.tsx
- src/components/ImageInput/InputModalContent.tsx
- src/components/Sidebar/index.tsx
- src/components/Todos/TodoContainer.tsx
- src/components/Todos/TodoItem.tsx
- src/components/Todos/TodoList.tsx
- src/components/Todos/TodoSection.tsx
- src/components/VerificationNote/VerificationNoteContainer/index.tsx
- src/components/VerificationNote/VerificationNoteFooter/index.tsx
- src/components/VerificationNote/VerificationNoteHeader/index.tsx
- src/components/VerificationNote/VerificationNoteImage/index.tsx
- src/components/VerificationNote/VerificationNoteTextarea/index.tsx
- src/constants/ApiEndpoints.ts
- src/constants/QueryKeys.ts
- src/constants/Todos/TodoFilter.ts
- src/hooks/apis/Todo/useCertifiedTodo.ts
- src/hooks/apis/Todo/useTodayTodo.ts
- src/hooks/useFilteredTodos.ts
- src/store/useVerificationNoteStore.ts
- 내 할 일 페이지 api 연동
- 인증 로직 구현 및 적용(사진 촬영 및 base64 등등)
- 이슈 번호: #91 
- 인증 관리에 필요한 store 수정(기존 노트 store)
- api 생성 및 해당하는 hook 구현
- type 지정 및 설정
아직 구현 안 된 부분이 있습니당 월요일 안에 리팩토링 전부 진행할 예정!
- 대시보드의 todoitem 타입이 다른 점 수정(Api로 보면서 확인해야 하는데 지금 스웨거 확인이 불가능해요)
- 대시보드에서 인증 시 `completeId` 설정이 되지 않는 부분 수정
- notify 에러, 성공 메세지 상수화
- 이미지 재촬영 로직 적용하기(구현은 해놨는데 확인을 못 해요 2)
- 파일 이름 통일하기 (인증 모달은 `CertifiedModal` 인데 안에서 사용하는 컴포넌트는 기범님이 만드신 `VerificationNote...` 이름이라 보는 저도 조금 헷갈려요)
- 파일 안의 로직 분리 및 컴포넌트 분리(한 파일에 코드가 좀 긴 거 같아서 분리할 예정입니다 특히 `TodoItem`)
- isLoading, isError일 때 처리 (isLoading 시에 스켈레톤, error일 때 notify 후 그 전 페이지로 이동으로 생각중입니다)
> [Feat] 내 할 일 페이지 api 연동 및 인증 로직 구현

- src/components/ConfirmationModal/index.tsx
- src/components/VerificationNote/VerificationNoteFooter/index.tsx
- src/constants/Messages.ts
- src/constants/ToastMessages.ts
- src/constants/keys.ts
- src/hooks/useVerificationNoteFooter.ts
- src/store/useToastStore.ts
- 로컬스토리지를 통한 임시저장 기능 구현
- 예, 아니오 등의 확인에 사용되는 모달 `ConfirmationModal` 구현
- 이슈 번호: #90 
- 로컬 스토리지를 통해 임시저장 구현했습니다
- 모달이 따로 필요해서 하나 만들어놨어요 이게 가장 범용적으로 사용될 수 있는 모달일 듯?
- 상수화를 따로 좀 빼놨는데 이런 관리가 괜찮으시다면 다른 부분을 최대한 다 빼둘 생각이에요
https://github.com/user-attachments/assets/cbe639d5-8305-47e2-a652-ac39d9e9f3c1
여기 분량이 좀 따로 나눠야 하는 부분인 거 같아서 짤라서 미리 올렸어요
근데 님들 중요한 부분이 있음 제가 기억이 잘 안 나는 거 같은데
임시저장을 할 때 작성하고 있던 목표와 할 일도 같이 저장이 되는건가요? 만약 저장된다고 하면 나중에 해당 목표나 할 일이 삭제되었을 때 관련 로직을 또 추가해서 임시저장 자체를 날려버리거나 하는 걸로 구분이 필요함...
만약 저장이 되지 않는다고 하면 임시저장을 할 때 미리 모달에다가 알려주기만 하면 되는 거라 간단해지긴 해요 어떤 게 나을까요
목표랑 할 일은 드롭다운으로 나와야 하는데 다른 곳에서 작업하고 있는 거라 아직 적용 덜 됐어용 ㅎ.ㅎ
머지하고 다른 쪽에서 적용하고 손보고 PR 또 올릴게여
> [Feat] 할 일 생성 모달 임시저장 기능 구현

- __test__/formatDateToRelativeTime.spec.ts
- __test__/isDatePast.spec.ts
- src/components/Dashboard/GoalList/GoalItem/ProgressLine/index.tsx
- src/components/Dashboard/GoalList/GoalItem/TodoList/TodoPic/index.tsx
- src/components/Dashboard/GoalList/GoalItem/TodoList/index.tsx
- src/components/common/Header/index.tsx
- src/hooks/apis/Todo/useCertifiedTodo.ts
- src/utils/date.ts
- 대시보드 인증 사진 적용
- 기타 수정
- 이슈 번호: #153
`isDatePast` 함수를 만들어 오늘 날짜 기준으로 해당 인증 날짜가 지났으면 회색으로 지나지 않았으면 해당 목표 색으로 변경하였습니다.
> Jest로 해당 함수 테스팅 진행하였습니다.
인증이 완료된 인증이면 해당 사진을 `opacity-50`으로 적용시켜 목표의 색을 보여주게 하였습니다. 
> 기존 피그마에서는 목표의 색을 opacity를 변경하였지만 반대의 값을 사진에 적용시켜 두었습니다. 피그마 기준으로 하면 opacity-30 적용시켜야 하지만 사진이 너무 안보여서 50으로 수정했습니다.
> 기존 디자인대로 오늘인증해야될 인증 기준으로 순서를 배치하면 현재 index 기반의 순서가 조금 애매하여 그냥 순서대로 두었습니다.
`onLoad`를 통해 이미지 로드가 느릴 경우 스켈레톤으로 나오도록 해두었습니다.
```js
<Image
src={pic}
fill
alt="인증 사진"
onLoad={() => setIsLoaded(true)}
className="rounded-16 object-cover opacity-50"
/>
```
<br />
예시 사진)
목표의 progress를 정수화 시켰습니다.
> 근데 노란색일 경우에 숫자가 잘 보이지않아 수정 필요할 것 같습니다.
https://github.com/user-attachments/assets/f358b202-5cc7-4ed0-b246-c689fa7e3199
https://github.com/user-attachments/assets/6108f986-6021-4d97-a2f3-3 …
> [Feat] add picture in dashboard

- src/app/(route)/goals/page.tsx
- src/components/Dashboard/GoalList/GoalItem/TodoList/TodoHeader/index.tsx
- src/components/Dashboard/GoalList/GoalItem/TodoList/index.tsx
- src/components/Dashboard/GoalList/GoalItem/index.tsx
- src/components/Dashboard/GoalList/index.tsx
- src/components/Goals/GoalList/index.tsx
- src/components/Sidebar/GoalList/index.tsx
- src/hooks/apis/Dashboard/useRecnetTodosQuery.ts
- src/hooks/apis/Dashboard/useTodayProgressQuery.ts
- src/hooks/apis/Dashboard/useTodosOfGoalsQuery.ts
- src/hooks/apis/Goals/useDeleteGoalMutation.ts
- src/hooks/apis/Goals/useEditGoalTitleMutation.ts
- src/hooks/apis/Goals/useGoalsDetailQuery.ts
- src/hooks/apis/Sidebar/useSidebarGoalsMutation.ts
- src/hooks/apis/Todo/useCertifiedTodo.ts
- src/hooks/apis/useGoalsQuery.ts
- src/hooks/useInfiniteScroll.ts
- src/types/data.ts
- src/types/response.ts
- 목표 페이지 무한 스크롤 적용
- 목표 페이지 목표 제목 수정 낙관적 업데이트 적용
- 타입 정리
- 이슈 번호: #152
대시보드 페이지와 동일하게 `useInfiniteQuery` 사용해서 무한 스크롤 구현했습니다.
> 무한 스크롤 관련 custom hook 만들어서 대시보드, 목표 페이지에서 동일하게 사용 가능하도록 했습니다.
> 현재 api로는 무한 스크롤 작동이 안되는데 대시보드와 동일하게 수정되면 작동 될 것 같습니다.
목표 제목 수정 시 낙관적 업데이트 적용 시켰습니다.
무한 스크롤 로직이 들어가서 사이드바 목표 추가와는 살짝 다르게 적용 시켰습니다.
일단 제가 사용하는 `useQuery`, `ueMutation` 관련 타입만 정리해두었습니다.
`response.ts` 파일에는 전체적인 응답 관련 타입을 정리해두었습니다.
> 기본 응답 타입 정의해두어서 `extends`로 가져다가 `data` 부분만 추가해서 사용할 수 있습니다.
```js
export interface BaseResponse {
statusCode: number;
timestamp: string;
}
export interface BaseInfiniteQueryResponse<T> {
pageParams: number[];
pages: T;
}
export interface RecentTodosResponse extends BaseResponse {
data: BasePageableTypes<TodoTypes[]>;
}
// ...
```
`data.ts` 파일에는 Goal, Todo, Complete 타입을 …
> [Feat] Add infinite scroll for goals page

- src/apis/Search/getSearch.ts
- src/app/(route)/search/page.tsx
- src/components/Search/SearchContent/SearchGoalList/index.tsx
- src/components/Search/SearchContent/SearchUserList/index.tsx
- src/components/Search/SearchContent/index.tsx
- src/components/Search/SearchInput/SearchFilterDropdown/index.tsx
- src/components/Search/SearchInput/index.tsx
- src/components/common/Header/index.tsx
- src/constants/ApiEndpoints.ts
- src/constants/QueryKeys.ts
- src/hooks/apis/Search/useSearchQuery.ts
- 검색 api, hook 생성 (쿼리 파라미터)
- header 컴포넌트의 검색페이지로의 라우터 설정
- 검색 로직 구현 (에러처리, 검색 리패치, 상태관리, 상태 초기화)
- 이슈 번호: #150 
검색 api와 hook을 분리한 이유는 기존의 HTTP service에서 제공된 GET의 코드를 수정하고 적용시켰지만 
쿼리 파라미터와 에러처리 때문에 다른 코드에서도 문제가 생길까봐! 일단 기존 방법으로 진행하였습니다.
api 함수에서 나온 에러 메시지를 받아 검색 결과에 적용을 시켰습니다.
드롭다운과 input의 값이 변경될 때마다 검색 결과를 바꾸는 것이 아닌
enter키를 누르거나 검색 아이콘을 눌렀을 때 결과가 실행되도록 의도를 하였기에 
enter키를 누르거나 검색 아이콘을 눌렀을 때마다 상태가 바뀌도록 처리하였습니다.
그 후 상태가 바뀔때마다 리패치를 시켜주었습니다. (쿼리 키 특정시키면 따로 처리안해줘도 될듯? 일단 우선적으로 이렇게 적용)
마지막으로 페이지를 나갔다가 들어오는 과정에서 상태값을 초기화 (안시켜주면 이전 데이터가 남아있음)
> [Feat] 검색 페이지 api 연동

- src/app/(route)/goals/page.tsx
- src/components/Dashboard/GoalList/GoalItem/TodoList/TodoHeader/index.tsx
- src/components/Dashboard/GoalList/GoalItem/TodoList/TodoPic/index.tsx
- src/components/Dashboard/GoalList/index.tsx
- src/components/Dashboard/RecentTodos/index.tsx
- src/components/Goals/GoalList/index.tsx
- src/components/Skeletons/GoalListSkeleton/index.tsx
- src/components/Skeletons/TodoListSkeleton/index.tsx
- src/components/common/EmptyStateText/index.tsx
- src/components/common/NoDataText/index.tsx
- src/components/common/Spinner/index.tsx
- src/constants/NoDataText.ts
- src/hooks/apis/Goals/useDeleteGoalMutation.ts
- src/utils/date.ts
- 무한 스크롤 스켈레톤 및 로딩 추가
- 할일 순서 및 정리
- 목표나 할일이 없을 경우 텍스트 정리
- 이슈 번호: #162 
무한 스크롤이 적용된 대시보드, 목표 페이지에 스켈레톤 적용 시켰습니다.
따로 `skeleton` 폴더에 정리해서 import 하는 방식으로 가져왔습니다.
스크롤해서 다음 데이터를 받아올 땐 스피너를 추가시켰습니다.
목표 페이지에서 종료된 할일은 기간대신 종료라고 나오고 순서를 `endDate` 기준으로 정렬하였습니다.
목표나 할일이 없을 경우 나타나는 텍스트를 `NoDateText` 컴포넌트로 나타낼 수 있도록 했습니다.
`constants` 폴더 안에 텍스트 정의해서 사용했습니다.
https://github.com/user-attachments/assets/5bd49a89-ce85-42fe-813b-cb3c6f1c05d1
> [Refactor] Add loading to infinite scroll

- src/app/(route)/myPage/page.tsx
- src/app/(route)/search/layout.tsx
- src/app/(route)/todos/[todoId]/layout.tsx
- src/app/(route)/todos/[todoId]/page.tsx
- src/app/(route)/userProfile/[userId]/layout.tsx
- src/components/Todos/TodoItem.tsx
- src/components/TodosDetail/TodosDetailContent/TodoDocs/index.tsx
- src/components/TodosDetail/TodosDetailContent/TodoProfile/index.tsx
- src/components/TodosDetail/TodosDetailContent/TodoRepeat/index.tsx
- src/components/TodosDetail/TodosDetailContent/index.tsx
- src/components/TodosDetail/TodosDetailHeader/index.tsx
- src/constants/ApiEndpoints.ts
- src/constants/QueryKeys.ts
- src/hooks/apis/Todo/useDeleteTodo.ts
- src/hooks/apis/Todo/useModifyTodo.ts
- src/hooks/apis/Todo/useTodoDetailQuery.ts
- src/types/data.ts
- src/types/response.ts
- 할일 상세보기 페이지 퍼블리싱
- todos 페이지에서 할일을 클릭하면 해당 todos/todoId 페이지로 이동하도록
- 할일 상세보기 데이터 get 커스텀 훅
- 할일 삭제 / 수정 로직 적용
- 이슈 번호: #165
할일 삭제 / 수정 로직 적용
- zustand를 사용하여 수정 시 todoId 포함 할일 상세 데이터들의 값을 저장하도록 했습니다.
-  수정/삭제 클릭 시 커스텀훅 적용
머지는 api가 변경되면 하도록 하겠습니다.
> [Feat] 할일 상세보기 페이지 (퍼블리싱, 할일 데이터, 할일 삭제수정)

- src/apis/services/httpMethod.ts
- src/app/(route)/userProfile/[userId]/page.tsx
- src/components/Search/SearchContent/SearchGoalList/index.tsx
- src/components/Search/SearchContent/SearchUserList/index.tsx
- src/components/UserProfile/UserProfileContent/index.tsx
- src/components/UserProfile/UserProfileHeader/index.tsx
- src/constants/ApiEndpoints.ts
- src/constants/QueryKeys.ts
- src/hooks/apis/Auth/useUserProfileQuery.ts
- src/hooks/apis/Follow/useAssignFollowMutation.ts
- src/hooks/apis/Follow/useDeleteFollowMutation.ts
- src/types/data.ts
- src/types/response.ts
- 타인 프로필 데이터 불러오기
- 팔로우 기능
- 이슈 번호: #160 
타인 프로필 데이터 불러오기
- 타인 프로필 데이터의 쿼리를 타인 userId를 이용하여 특정하였음.
팔로우 기능
- 낙관적 업데이트를 이용하여 사용자의 경험을 개선함.
추후에 불필요한 중복된 api들은 상의한 다음 제거하도록 하겠습니다.
> [Feat] 타인 프로필 페이지 (데이터 불러오기, 팔로우 기능)

- src/app/(auth)/layout.tsx
- src/app/(route)/dashboard/page.tsx
- src/app/(route)/goals/page.tsx
- src/app/(route)/layout.tsx
- src/app/(route)/myPage/page.tsx
- src/app/(route)/search/layout.tsx
- src/app/(route)/search/page.tsx
- src/app/(route)/todos/[todoId]/layout.tsx
- src/app/(route)/todos/[todoId]/page.tsx
- src/app/(route)/userProfile/[userId]/layout.tsx
- src/app/(route)/userProfile/[userId]/page.tsx
- src/app/layout.tsx
- src/components/Dashboard/GoalList/index.tsx
- src/components/Follows/FollowsContainer.tsx
- src/components/Sidebar/MenuItem/index.tsx
- src/components/Sidebar/Profle/index.tsx
- src/components/Sidebar/SidebarButton/index.tsx
- src/components/Sidebar/index.tsx
- src/components/Skeletons/FollowsSkeleton/index.tsx
- src/components/Todos/TodoContainer.tsx
- src/components/common/PageContainer/index.tsx
- src/provider/QueryProvider.tsx
- 레이아웃을 모바일에서 테블릿 크기로 설정
- 이슈 번호: #177 
`PageContainer`라는 컴포넌트를 만들어서 각각의 페이지안에 넣었습니다.
데스크탑으로 들어갔을 경우에는 780의 크기로 보여집니다.
그 아래로는 모바일 기준과 동일한 레이아웃을 가집니다.
예시) 목표 페이지
```js
import { Header } from '@/components/common/Header';
import { PageContainer } from '@/components/common/PageContainer';
import { GoalList } from '@/components/Goals/GoalList';
export default function GoalsPage() {
return (
<>
<Header />
<PageContainer>
<h1 className="pl-4 pt-16 text-xl-semibold">목표</h1>
<GoalList />
</PageContainer>
</>
);
}
```
> 팔로우 페이지는 현재 main 브랜치 기준으로 미완료 페이지라 일단 제외하고 작업했습니다.
> 영준님 PR 올라오면 반영해서 수정하고 머지하면 될 것 같습니다
https://github.com/user-attachments/assets/c5e12c0b-4699-43d3-94ff-2fdb5dd8b68f
> [Feat] Force mobile layout

- src/app/(route)/page.tsx
- src/components/Dashboard/Follower/FollowerStory/index.tsx
- src/components/Dashboard/GoalList/GoalItem/TodoList/TodoPic/index.tsx
- src/components/Follows/Post/PostImage.tsx
- src/components/Follows/Post/PostProfile.tsx
- src/components/MyPage/MyProfile/index.tsx
- src/components/Search/SearchContent/SearchGoalList/index.tsx
- src/components/Search/SearchContent/SearchUserList/index.tsx
- src/components/Sidebar/Profle/index.tsx
- src/components/Sidebar/index.tsx
- src/components/TodoModal/TodoModalDocs/FileUpload/index.tsx
- src/components/Todos/TodoItem.tsx
- src/components/TodosDetail/TodosDetailContent/TodoDocs/index.tsx
- src/components/TodosDetail/TodosDetailContent/TodoProfile/BasicTodoItem/index.tsx
- src/components/TodosDetail/TodosDetailHeader/index.tsx
- src/components/UserProfile/UserProfileContent/index.tsx
- src/components/UserProfile/UserProfileHeader/index.tsx
- src/components/VerificationNote/VerificationNoteImage/index.tsx
- src/constants/dropdown.ts
- src/middleware.ts
- 할일 상세보기 리팩토링, 메인 페이지 미들웨어 설정
- 이슈 번호: #183 
할 일 상세보기의 드롭다운 적용
저희가 생각하는 메인페이지는 /dashboard이고
로그인 한 유저가 사이트를 껐다 키면 / (홈으로) 이동하여서 소개하는 느낌의 글로 지정해두려고 했으나
디자인이 애매하여
미들웨어 설정에서 로그인을 이미한 경우 홈 화면에서 대시보드 페이지로 리다이렉션 되도록 구현하였습니다.
> [Refactor] 할일 상세보기 리팩토링, 메인 페이지 미들웨어 설정

- .github/workflows/storybook.yml
- next.config.ts
- src/apis/UserProfile/getUserProfile.ts
- src/app/(route)/userProfile/[userId]/page.tsx
- src/components/UserProfile/UserProfileContent/index.tsx
- src/components/UserProfile/UserProfileHeader/index.tsx
- 타인 프로필 페이지 SSR 적용
- 이미지 최적화
[내용 정리 블로그](https://velog.io/@keyboy/SSR-%EA%B5%AC%ED%98%84-%ED%8A%B8%EB%9F%AC%EB%B8%94%EC%8A%88%ED%8C%85-401-%EC%9D%B8%EC%A6%9D%EC%BF%A0%ED%82%A4-%EC%98%A4%EB%A5%98)
- 이슈 번호: #194 
타인 프로필 페이지 SSR 적용 전에 LCP 성능이 매우 안좋았고 이후 이미지가 많아지면 더욱 안좋아질 것이라고 생각하였습니다.
따라서 LCP 요소를 서버에서 미리 렌더링을 할 수 있는 SSR 방식과 이미지 최적화를 적용하기로 하였습니다.
SSR은 api 함수를 따로 만들어 token 값을 서버 컴포넌트로부터 받도록 설정
이미지 최적화는 avif 파일 형식, sizes, priority 속성을 사용
또한 이미지 화질과 크기의 개선이 필요하였습니다.
TBT 성능이 안좋아서 이를 개선중에 있습니다.
또한 빌드 오류 같은 경우는
https://github.com/pnpm/pnpm/issues/9014
해당 이슈를 참고하였습니다.
1️⃣ 문제 발생 원인
GitHub Actions에서 corepack prepare pnpm@latest-10 --activate 실행 시 키 인증 오류
기존 pnpm이 충돌하여 설치 중 오류 발생
2️⃣ 해결 방법
GitHub Actions에서 Corepack을 최신 버전으로 업데이트
기존 pnpm이 존재하면 삭제 후 다시 설치
3️⃣ 왜 로컬 pnpm을 변경하지 않는가?
CI/CD에서만 발생하는 문제이므로, …
> [Refactor] 타인 프로필 페이지 SSR 적용 및 이미지 최적화

- src/components/Follows/FollowsContainer.tsx
- 또한 UI 개선 (팔로우 페이지 팔로우 게시물이 없는 경우)
- TBT가 성능이 배포환경과 로컬환경이 달라 이를 확인중
- 이슈 번호: #196 
심플하게 해봤어용
추가적인 개선 사항은 업데이트 될 예정입니다.
> [Refactor] 팔로우 페이지 UI 개선 및 성능 개선(진행중)

- src/apis/services/httpMethod.ts
- src/app/(route)/dashboard/page.tsx
- src/app/(route)/layout.tsx
- src/app/not-found.tsx
- src/components/Dashboard/RecentTodos/index.tsx
- src/hooks/apis/Dashboard/useRecentTodosQuery.ts
- src/hooks/apis/Dashboard/useTodayProgressQuery.ts
- src/hooks/apis/useGoalsQuery.ts
- src/lib/axiosInstance.ts
- GET 함수 변경
- 최근 등록한 할일 SSR
- not-found page 사이드바 삭제
- 이슈 번호: #199 
- 토큰을 헤더에 추가하는 작업이 `axios`의 `interceptor`에서 `document` 객체를 활용해 브라우저에서만 가능한 방식이라 서버 컴포넌트에서 토큰을 넘겨주는 방식도 추가시켰습니다.
- `props`에 토큰이 있으면 `setAuthToken` 함수로 헤더에 넣어줍니다.
- 대시보드에서 최근 등록한 할일 부분에서 `isLoading`으로 로딩을 관리하는 것보다 `Suspense`로 관리하는 것이 좋을 것 같아 변경하였습니다.
- 새로고침 했을 때 기존에 캐시되어 있는 값을 사용해 더 빠른 초기 로딩이 가능해졌습니다
> 무한 스크롤 있는 부분은 적용해보려다가 에러 해결을 못해서 아직 적용은 못시켰습니다..
- 먼저 빌드 에러가 나서 확인해봤는데 not-found 페이지가 로그인 이전에도 나타날 수 있는 화면이라 그냥 사이드바를 삭제시켰습니다.
- 사이드바에서는 로그인을 했을 때 나타나는 정보들이 있어서 없애도 될 것 같습니다.
기존
https://github.com/user-attachments/assets/3814d04c-eb2a-477b-b31d-027707a572a7
적용 후
https://github.com/user-attachments/assets/f12d2e9d-849c-4c84-949d-9ca55d6f632c
> [Refactor] improve api function

- src/apis/services/httpMethod.ts
- src/hooks/apis/Auth/useChangePassword.ts
- src/hooks/apis/Auth/useFollowCountQuery.ts
- src/hooks/apis/Auth/useModifyProfilePic.ts
- src/hooks/apis/Auth/useUserProfileQuery.ts
- src/hooks/apis/Auth/useWithdrawal.ts
- src/hooks/apis/Comment/useCreateCommentQuery.ts
- src/hooks/apis/Comment/useDeleteCommentQuery.ts
- src/hooks/apis/Comment/usePutCommentQuery.ts
- src/hooks/apis/Complete/useGetCompleteDetailQuery.ts
- src/hooks/apis/Dashboard/useRecentTodosQuery.ts
- src/hooks/apis/Dashboard/useTodayProgressQuery.ts
- src/hooks/apis/Dashboard/useTodosOfGoalsQuery.ts
- src/hooks/apis/Follow/useAssignFollowMutation.ts
- src/hooks/apis/Follow/useDeleteFollowMutation.ts
- src/hooks/apis/Follows/useDeleteFollowsQuery.ts
- src/hooks/apis/Follows/useGetFollowPostsQuery.ts
- src/hooks/apis/Goals/useDeleteGoalMutation.ts
- src/hooks/apis/Goals/useEditGoalTitleMutation.ts
- src/hooks/apis/Goals/useGoalsDetailQuery.ts
- src/hooks/apis/Likes/useDeleteLikeQuery.ts
- src/hooks/apis/Sidebar/useSidebarGoalsMutation.ts
- src/hooks/apis/Todo/useTodayTodo.ts
- src/hooks/apis/Todo/useTodoDetailQuery.ts
- src/hooks/apis/useGoalsQuery.ts
- src/hooks/apis/useUserQuery.ts
- src/lib/query/getQueryClient.ts
- src/utils/handleHttpError.ts
- API 함수를 하나로 통합
- 에러처리 통합
- 이슈 번호: #203
기존 API 함수를 하나로 통합
> [Refactor] api 요청 함수 최적화
